<?php
/** @var \Ziffity\CustomFrame\Block\Adminhtml\Edit\Label $block */
?>
<?php if ($block->loadWidget()): ?>
<div class="admin-topbot-wr hidden-wr">
    <h4 class="loading">Loading...</h4>
    <div class="antool-render">
        <canvas class="topbot-render" data-mod="labels"></canvas>
    </div>
    <div id="tool-controls-labels" class="antool-controls antool-cols">
        <div class="antool-controls-col">
            <div class="antool-controls-main">
                <button @click="addLayerText"
                        title="Add label"
                        type="button"
                        class="scalable add">
                    <span>
                        <span>
                            <span>
                                Add Text label
                            </span>
                        </span>
                    </span>
                </button>
            </div>
            <div class="antool-controls-list">
                <div v-for="(index, layer) in reverseList(list_text)"
                     class="antool-controls-item"
                     track-by="$index"
                     v-bind:class="{active: layer.active}">
                    <h3>{{layer.name}}</h3>
                    <div class="controls-item-tool">
                        <h4>Label Size:</h4>
                        <i>{{layer.width_inch}}" Wide x {{layer.height_inch}}" High</i>
                    </div>
                    <div class="controls-item-tool">
                        <h4>Input Text for Label:</h4>
                        <div class="row-input">
                                <textarea v-model="layer.text"
                                          v-on:input="changeText(layer)"
                                          name="{{mod_name}}-text-{{index}}"
                                          id="{{mod_name}}-text-{{index}}"
                                          cols="30"
                                          rows="10"
                                          placeholder="Start typing…">{{*layer.text}}</textarea>
                        </div>
                    </div>
                    <div class="controls-item-tool">
                        <h4>Font Style &amp; Size:</h4>
                        <div class="f-input-2 tool-row">
                            <div class="f-input-part row-input form-select-box">
                                <div class="tool-row">
                                    <select
                                        v-model="layer.font"
                                        @change="changeFontFam(layer)"
                                        name="{{mod_name}}-font-list-{{index}}"
                                        id="{{mod_name}}-font-list-{{index}}">
                                        <option v-for="font in fonts"
                                                v-bind="{selected: (layer.font === font)}"
                                                v-bind:style="{'font-family': font}"
                                                value="{{font}}">{{font}}</option>
                                    </select>
                                </div>

                                <div class="f-input-3 row-input">
                                    <div class="input-icon-text-bold input-icon-text f-input-part">
                                        <input v-model="layer.font_style.bold"
                                               @change="setFontWeight(layer)"
                                               id="{{mod_name}}-text-style-bold-{{index}}"
                                               type="checkbox">
                                        <label for="{{mod_name}}-text-style-bold-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M15.3 10.3c0.3-0.4 0.5-0.8 0.5-1.3 0-0.5-0.1-0.9-0.4-1.3s-0.6-0.7-1.1-0.9c-0.5-0.2-1.3-0.3-2.4-0.3H7.1v0.3c0.5 0 0.8 0 0.9 0.1 0.2 0.1 0.3 0.2 0.3 0.3S8.5 7.7 8.5 8.3v6.4c0 0.5 0 0.9-0.1 1s-0.2 0.2-0.3 0.3 -0.5 0.1-0.9 0.1v0.3h5c1.4 0 2.5-0.3 3.2-0.9 0.6-0.5 0.9-1.1 0.9-1.9 0-0.7-0.3-1.3-0.8-1.7 -0.4-0.3-1-0.6-2-0.8C14.4 11 15 10.7 15.3 10.3zM10.8 7.1c0.7 0 1.2 0.1 1.6 0.2s0.6 0.4 0.7 0.6c0.2 0.3 0.3 0.6 0.3 1.1 0 0.4-0.1 0.8-0.3 1.1s-0.4 0.5-0.8 0.7c-0.3 0.2-0.8 0.2-1.5 0.2V7.1zM12.5 11.8c0.4 0.1 0.7 0.4 0.9 0.8 0.2 0.4 0.3 0.8 0.3 1.2 0 0.4-0.1 0.8-0.3 1.1 -0.2 0.3-0.4 0.6-0.8 0.8 -0.3 0.2-0.7 0.3-1.1 0.3 -0.3 0-0.5-0.1-0.6-0.2 -0.1-0.1-0.2-0.3-0.2-0.6l0-0.4v-3.2C11.6 11.5 12.1 11.6 12.5 11.8z"></path></svg>
                                        </label>
                                    </div>
                                    <div class="input-icon-text-italic input-icon-text f-input-part">
                                        <input v-model="layer.font_style.italic"
                                               @change="setFontStyle(layer)"
                                               id="{{mod_name}}-text-style-italic-{{index}}"
                                               type="checkbox">
                                        <label for="{{mod_name}}-text-style-italic-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M11.2 15.6c-0.1 0-0.2-0.1-0.3-0.2s-0.1-0.2-0.1-0.3c0-0.2 0.1-0.5 0.2-1.1l1.7-6c0.2-0.6 0.3-1 0.4-1.2s0.3-0.3 0.5-0.4c0.2-0.1 0.4-0.1 0.7-0.1l0.1-0.3h-3.8l-0.1 0.3c0.4 0 0.6 0 0.8 0.1 0.1 0 0.2 0.1 0.3 0.2 0.1 0.1 0.1 0.2 0.1 0.3 0 0.3-0.1 0.6-0.2 1.1l-1.7 6c-0.2 0.6-0.3 1-0.5 1.2 -0.1 0.1-0.3 0.3-0.5 0.3 -0.1 0.1-0.4 0.1-0.8 0.1L7.9 16h4.1l0.1-0.3C11.7 15.7 11.4 15.7 11.2 15.6z"></path></svg>
                                        </label>
                                    </div>
                                    <div class="input-icon-text-underline input-icon-text f-input-part">
                                        <input v-model="layer.font_style.underline"
                                               @change="setFontDecoration(layer)"
                                               id="{{mod_name}}-text-style-underline-{{index}}"
                                               type="checkbox">
                                        <label for="{{mod_name}}-text-style-underline-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M14 5.3c0.4 0 0.7 0.1 0.9 0.3 0.1 0.2 0.2 0.5 0.2 1.2v4c0 1.1-0.1 1.8-0.3 2.2 -0.2 0.4-0.5 0.8-1.1 1.1s-1.1 0.4-1.7 0.4c-0.5 0-0.9-0.1-1.3-0.3 -0.3-0.2-0.6-0.4-0.8-0.7 -0.2-0.3-0.3-0.7-0.4-1.2s-0.1-0.9-0.1-1.3V6.8c0-0.6 0.1-0.9 0.2-1.1 0.2-0.3 0.5-0.4 0.9-0.4h0.4V5H6.5v0.3h0.4c0.4 0 0.6 0.1 0.8 0.3s0.3 0.6 0.3 1.2v3.9c0 1.2 0.1 2 0.2 2.4 0.2 0.6 0.6 1.1 1.2 1.5 0.6 0.4 1.4 0.6 2.5 0.6 1 0 1.8-0.2 2.4-0.6 0.6-0.4 1-0.9 1.2-1.4 0.2-0.5 0.3-1.3 0.3-2.3V6.8c0-0.6 0.1-0.9 0.2-1.1 0.2-0.3 0.5-0.5 0.9-0.5h0.4V5h-3.5v0.3H14z"></path><path d="M6.5 18.4v-0.7h10.8v0.7H6.5z"></path></svg>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="f-input-2 tool-row">
                            <div class="f-input-moreless f-input-part row-input">
                                <div class="tool-row">
                                    <div class="label">Size:</div>
                                    <div class="moreless-wr">
                                        <a @click.prevent="increaseFont(layer, list_text.length - index - 1)"
                                           class="more"
                                           href="#link"></a>
                                        <a @click.prevent="decreaseFont(layer, list_text.length - index - 1)"
                                           class="less"
                                           href="#link"></a>
                                    </div>
                                </div>

                                <div class="f-input-3 row-input">
                                    <div class="input-icon-text-left input-icon-text f-input-part">
                                        <input v-model="layer.text_align"
                                               @change="setTextAlign(layer)"
                                               value="left"
                                               id="{{mod_name}}-text-align-left-{{index}}"
                                               name="{{mod_name}}-text-align-{{index}}"
                                               type="radio">
                                        <label for="{{mod_name}}-text-align-left-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><rect x="4.5" y="17.2" width="15.6" height="1.4"></rect><rect x="11.6" y="14.3" width="8.5" height="1.4"></rect><rect x="5.9" y="11.5" width="14.2" height="1.4"></rect><rect x="3.1" y="8.7" width="17" height="1.4"></rect><rect x="8.8" y="5.8" width="11.3" height="1.4"></rect></svg>
                                        </label>
                                    </div>
                                    <div class="input-icon-text-center input-icon-text f-input-part">
                                        <input v-model="layer.text_align"
                                               @change="setTextAlign(layer)"
                                               value="center"
                                               id="{{mod_name}}-text-align-center-{{index}}"
                                               name="{{mod_name}}-text-align-{{index}}"
                                               type="radio">
                                        <label for="{{mod_name}}-text-align-center-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><rect x="3.6" y="6.2" width="16" height="1.3"></rect><rect x="3.6" y="16.9" width="16" height="1.3"></rect><rect x="7.6" y="8.9" width="8" height="1.3"></rect><rect x="7.6" y="14.2" width="8" height="1.3"></rect><rect x="4.9" y="11.5" width="13.3" height="1.3"></rect></svg>
                                        </label>
                                    </div>
                                    <div class="input-icon-text-right input-icon-text f-input-part">
                                        <input v-model="layer.text_align"
                                               @change="setTextAlign(layer)"
                                               value="right"
                                               id="{{mod_name}}-text-align-right-0"
                                               name="{{mod_name}}-text-align-{{index}}"
                                               type="radio">
                                        <label for="{{mod_name}}-text-align-right-{{index}}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><rect x="4.5" y="17.2" width="15.6" height="1.4"></rect><rect x="11.6" y="14.3" width="8.5" height="1.4"></rect><rect x="5.9" y="11.5" width="14.2" height="1.4"></rect><rect x="3.1" y="8.7" width="17" height="1.4"></rect><rect x="8.8" y="5.8" width="11.3" height="1.4"></rect></svg>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="f-input-part size-view">{{layer.font_size_inch}}</div>
                        </div>
                    </div>
                    <div class="controls-item-tool">
                        <div class="label">Font Color:</div>
                        <div class="color-list row-input">
                            <div v-for="color in text_colors"
                                 class="color-item">
                                <input v-model="layer.text_color"
                                       @change="setTextColor(layer)"
                                       name="{{mod_name}}-color-{{index}}"
                                       id="{{mod_name}}-color-{{index}}-{{$index}}"
                                       value="{{color}}"
                                       type="radio">
                                <label for="{{mod_name}}-color-{{index}}-{{$index}}"
                                       v-bind:style="{'background-color': color}"></label>
                            </div>
                        </div>
                    </div>
                    <div class="controls-item-tool">
                        <a @click.prevent="removeLayer(layer, 'text')"
                           href="#link"
                           class="font-gold external-tab-link">X <span>Remove</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="antool-controls-col">
            <div class="antool-controls-main">
                <button @click="addLayerImage"
                        title="Add label"
                        type="button"
                        class="scalable add">
                    <span>
                        <span>
                            <span>
                                Add Image label
                            </span>
                        </span>
                    </span>
                </button>
            </div>
            <div v-for="(index, layer) in reverseList(list_images)"
                 class="antool-controls-item"
                 track-by="$index"
                 v-bind:class="{active: layer.active}">
                <h3>{{layer.name}}</h3>
                <div class="controls-item-tool"
                     v-show="!layer.url">
                    <input @change="changeLayerImage($event, layer, list_images.length - index - 1)"
                           type="file"
                           id="layer-{{mod_name}}-upload-{{index}}">
                    <label for="layer-{{mod_name}}-upload-{{index}}"
                           class="form-button">
                        UPLOAD IMAGE
                    </label>
                </div>
                <div class="controls-item-toolo"
                     v-show="layer.url">
                    <div class="label">Label Size:</div>
                    <i>{{layer.width_inch}}" Wide x {{layer.height_inch}}" High</i>
                </div>
                <a @click.prevent="removeLayer(layer, 'images')"
                   class="font-gold external-tab-link"
                   href="#link">X <span>Remove</span></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.productJson = <?php echo $block->getProductJson(); ?>;
</script>
<?php endif;?>
