<?php

namespace Ziffity\Coproduct\Model\Product\Attribute\Frontend;

use Magento\Eav\Model\Entity\Attribute\Source\BooleanFactory;
use Magento\Framework\App\CacheInterface;
use Magento\Framework\Serialize\Serializer\Json as Serializer;
use Magento\Store\Model\StoreManagerInterface;
use Ziffity\Coproduct\Model\Evaluate;

class GetSizeModel extends \Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend
{

    protected $lookupFunction;

    public function __construct(
        BooleanFactory        $attrBooleanFactory,
        Evaluate              $lookupFunction,
        CacheInterface        $cache = null,
                              $storeResolver = null,
        array                 $cacheTags = null,
        StoreManagerInterface $storeManager = null,
        Serializer            $serializer = null
    )
    {
        $this->lookupFunction = $lookupFunction;
        parent::__construct($attrBooleanFactory, $cache, $storeResolver, $cacheTags, $storeManager, $serializer);
    }

    public function getValue(\Magento\Framework\DataObject $object)
    {
        // TODO: Change the autogenerated stub to processed value later.
        return parent::getValue($object);
    }

}
