<?php

/** @var $block \Magento\Framework\View\Element\Template */
?>
<?php
$buttonTitle = __('Save Design');
?>
<div class="save-design">
    <button
            title="<?= $buttonTitle ?>"
            class="action primary"
            id="product-save-design" data-mage-init='{"Ziffity_SavedDesigns/js/catalog-save-design":{}}' disabled>
        <span><?= $buttonTitle ?></span>
    </button>
</div>
