<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Items\Column\Name
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
$selectionsHelper = $this->helper(Ziffity\ProductCustomizer\Helper\Selections::class);
?>
<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= (int) $_item->getId() ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU'))?>:</span>
        <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($_option) ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <?php $id = 'id' . uniqid(); ?>
                        <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */ $id; ?>">
                                <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */ $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                             "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $id . "').show();});" .
                              PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */ $dots .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $id .
                                 "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */ $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */ $dots .
                                 "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>



<?php  if($_item->getProductType() == "customframe"): ?>
    <?php
    $completedSteps = $selectionsHelper->getCompletedStepsFromOptions($_item->getAdditionalData());
    $data =  $selectionsHelper->getUnserializedData($_item->getAdditionalData());
    $product = $selectionsHelper->getProduct($_item->getProductId());
    $selections  = $selectionsHelper->getSelections($data, $product, $completedSteps);
    $coProducts = $_item->getCustomizerDetails() ? $selectionsHelper->getUnserializedData($_item->getCustomizerDetails()): null;
    ?>
<details>
    <summary>General</summary>
    <dl>
        <?php  foreach($selections as $key => $selection):
            if(!isset($selection['label'])){?>

            <dt>
            <strong><?= $key ?></strong>
           </dt>
            <dd>
                <?php foreach ($selection as $key => $sel): ?>
                <div>
                    <span><?= $sel['label'] ?></span>&nbsp;-&nbsp;
                    <span><?= $sel["value"] ?></span>
                </div>
                <?php endforeach; ?>
            </dd>
            <?php } else { ?>
                <dt>
                    <strong><?= $selection["label"] ?></strong>
                </dt>
                <dd><?= $selection["value"] ?></dd>
        <?php } ?>
       <?php endforeach; ?>
        <?php if($coProducts): ?>
            <?php foreach ($coProducts as $key => $products):?>
                <dt>
                    <strong><?= $key ?></strong>
                </dt>
                <dd>
                    <?php foreach ($products as $key => $sel): ?>
                       <?php if($sel): ?>
                        <div>
                            <span><?= $key ?></span>&nbsp;-&nbsp;
                            <span><?= $sel ?></span>
                        </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dd>
            <?php endforeach; ?>

        <?php endif; ?>
    </dl>
</details>
<?php endif; ?>

